### ISSUE TITLE
Не могу создать регион или функция Создать регион нективна.

### ISSUE THREAD

**Issue by k0de1ne** [qPexLegendary/DGuard#1]
Я попробовал отметить точки региона как топором так и через команды pos. Но при попытке создать регион снова пишет что нужно отметить обе точки.
Возможно это ошибка. Координаты точек пропадают.

**Comment by gititems246** [comment]
+

**Comment by k0de1ne** [comment]
Функция Создать регион не работает.

**Comment by ScarletRedMan** [comment]
Исправлено
