### ISSUE TITLE
Как скачатт

### ISSUE THREAD

**Issue by ProGames7569** [qPexLegendary/DGuard#11]
Как скачать?

**Comment by ScarletRedMan** [comment]
Скачай файлы проекта, далее перемести папку DGuard в папку с плагинами. Также тебе потребуется плагины FormAPI и DevTools для его запуска. Сейчас пока-что не рекомендую использовать DGuard, пока не выпущу обновление для него, которое исправляет множество проблем с плагином

**Comment by ProGames7569** [comment]
А где папка

**Comment by ProGames7569** [comment]
С файлом

**Comment by ScarletRedMan** [comment]
Еще раз прочти то, что я написал тебе выше. Там все понятным языком написано
