### ISSUE TITLE
Помогите разработчики!!!

### ISSUE THREAD

**Issue by gititems246** [qPexLegendary/DGuard#2]
Помогите пожалуйста!!! Я не могу создать регион, ссылка на видео с багом, исправьте пожалуйста! https://yadi.sk/d/UUF09iswpLe17Q

**Comment by gititems246** [comment]
С командами /rg pos1 и /rg pos2 тоже самое!!!!!

**Comment by ScarletRedMan** [comment]
Хорошо, сейчас исправлю. Спасибо за видео

**Comment by ScarletRedMan** [comment]
Исправлено
