### ISSUE TITLE
Исправьте баг!!! 

### ISSUE THREAD

**Issue by gititems246** [qPexLegendary/DGuard#3]
Сказали что исправили хрень, но вы другую хрень не исправили!! Создать регион не могу, пишет (Для начала отметьте крайние точки региона) Хотя я топориком две точки отметил, и с /rg pos1 и /rg pos2 тоже самое!!!

**Comment by ScarletRedMan** [comment]
Хорошо, сейчас опять посмотрю

**Comment by ScarletRedMan** [comment]
Исправлено
