### ISSUE TITLE
Новый баг! 

### ISSUE THREAD

**Issue by gititems246** [qPexLegendary/DGuard#4]
Во первых, хотел бы поблагодарить за исправление предыдущего бага, но я нашёл новый баг!!!
Суть бага: когда хочешь отметить точки 1 и 2 с помощью топора, то получается баг!
(подробнее на видео) - https://yadi.sk/d/BST4auR2W06g2Q

С /rg pos1 и /rg pos2 всё работает СТАБИЛЬНО!!!

**Comment by ScarletRedMan** [comment]
Там нужно будет сейчас переписывать систему отметки точек, ибо тогда я ее сделал очень коряво. Щас займусь этим

**Comment by gititems246** [comment]
А скоро готово будет?

**Comment by ScarletRedMan** [comment]
Мне там осталось сделать совсем немного. Но я к сожалению сейчас не в городе.

> А скоро готово будет?

**Comment by gititems246** [comment]
> Мне там осталось сделать совсем немного. К сожалению, сейчас не в городе.
> 
> > А скоро готово будет?

Эх, поскорее бы!

**Comment by gititems246** [comment]
а долго ещё?

**Comment by gititems246** [comment]
а скоро готово будет?
